version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# python:
#   install:
#     - requirements: docs/requirements.txt
#     - method: pip
#       path: .

conda:
  environment: docs/soliket-docs.yml

formats: all
