version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

conda:
  environment: soliket-tests.yml

build:
  os: ubuntu-22.04

formats: all
