comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
github_checks:
    annotations: false
