name: Compatibility
on:
  schedule:
    - cron: '0 4 * * SUN'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv and dependencies
        run: |
          pip install uv
          bash ci_scripts/install_deps.sh --extras dev emulator --python ${{ matrix.python-version }}
      - name: Run tests
        env:
          COBAYA_PACKAGES_PATH: ./cobaya_packages
        run: |
          uv run pytest -vv --durations=10
